version: '3'
services:
  gateway:
    build: "./services/gateway"
    ports:
      - 8000:8000

  redis:
    image: redis:7.0.2-alpine3.16

  mailhog:
    image: mailhog/mailhog:v1.0.1
    ports:
      - 8001:8025

  rabbitmq:
    image: rabbitmq:3.9.17-alpine

  users:
    build: "./services/user"
    depends_on:
      - users_db
  users_db:
    image: postgres:14.3-alpine3.16
    environment:
      - POSTGRES_USER=users
      - POSTGRES_PASSWORD=users
      - POSTGRES_DB=users
  
  employees:
    build: './services/employee'
    depends_on:
      - employees_db
  employees_db:
    image: postgres:14.3-alpine3.16
    environment:
      - POSTGRES_USER=employees
      - POSTGRES_PASSWORD=employees
      - POSTGRES_DB=employees

  bookings:
    build: './services/booking'
    depends_on:
      - bookings_db
  bookings_db:
    image: postgres:14.3-alpine3.16
    environment:
      - POSTGRES_USER=bookings
      - POSTGRES_PASSWORD=bookings
      - POSTGRES_DB=bookings

  movies:
    build: './services/movie'
    depends_on:
      - movies_db
  movies_db:
    image: postgres:14.3-alpine3.16
    environment:
      - POSTGRES_USER=movies
      - POSTGRES_PASSWORD=movies
      - POSTGRES_DB=movies