POST /api/v1/users/signup
Host: localhost:8000
Content-Type: application/json

{
  "Email": "test@mailer.com",
  "Name": "testuser",
  "Password": "123456"
}

####
POST /api/v1/users/signin
Host: localhost:8000
Content-Type: application/json

{
  "Email": "test@mailer.com",
  "Password": "123456"
}
