POST /api/v1/bookings
Host: localhost:8000
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2NzAxNjA4NjMsImlhdCI6MTY3MDE1NzI2MywiVXNlcklEIjoxfQ.ogAa4RptBmsSNgZR7nu90x566dmQcxkSXUil7fxEa7w
Content-Type: application/json

{
  "ScheduleID": 2
}

####
GET /api/v1/bookings
Host: localhost:8000
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2NzAxNjA4NjMsImlhdCI6MTY3MDE1NzI2MywiVXNlcklEIjoxfQ.ogAa4RptBmsSNgZR7nu90x566dmQcxkSXUil7fxEa7w